name: Hello World Training Workflow

on:
  workflow_dispatch:

jobs:
  greet:
    env:
            MY_ENV: "John Doe"
    runs-on: ubuntu-latest
    steps:
    - name: Run a multi-line script
      run: |
          echo "Hello $MY_ENV"
          echo "Hello $GITHUB_ACTOR" 
          echo "Config variable: ${{vars.PROJECTID}}"
          echo "Context var: ${{github.workflow}}"
          echo "secret : ${{secrets.GITHUB_TOKEN}}"
          echo "secret : ${{secrets.SONAR_TOKEN}}"
          echo "ref: ${{github.ref_name}}"
     # List all files in the current directory for comparison before and after actions/checkout@v5.
    -  run: ls -l
    - uses: actions/checkout@v5
    - run: ls -l
    
